public class CalculatorReturn {
    
 Public integer addition(integer a, integer b)
    {
        integer c= a + b;
      return c; 
    }
    
    Public integer subtraction(integer a, integer b)
    {
        integer c= a - b;
        return c;
    }
 Public integer multiplication(integer a, integer b)
    {
        integer c= a * b;
        return c;
    }
    Public integer division(integer a, integer b)
    {
        integer c= a / b;
       return c;
    }
     Public double modulus( integer a ,integer b)
    {
        double c=math.mod(a,b);
       return c;
    }
    
}